apiVersion: apps/v1
kind: Deployment
metadata:
    name: heron-redux
    labels:
      app: heron-redux
spec:
    replicas: 1
    selector:
        matchLabels:
            app: heron-redux
    template:
        metadata:
            labels:
                app: heron-redux
        spec:
            containers:
                - name: heron-redux
                  image: stephenc0821/heron-clone:{{ .Values.env.APP_VERSION }}
                  ports:
                    - containerPort: 80
                  env:
                  - name: REACT_APP_SERVICE_ID
                    value: Changeme
                  - name: REACT_APP_TEMPLATE_ID
                    value: Changeme
                  - name: REACT_APP_PUBLIC_KEY
                    value: Changeme
                  - name: REACT_APP_PROTOCOL_LINK
                    value: https://www.protocols.io/view/heron-data-suite-biomedical-quantitative-analysis-8epv5xwj5g1b/v1
                  - name: REACT_APP_GLYCO_API
                    value: http://localhost:8000
                  readinessProbe:
                    httpGet:
                        path: /health
                        port: 80
                    initialDelaySeconds: 10
                    periodSeconds: 10
                    successThreshold: 1
                    failureThreshold: 3
                  livenessProbe:
                    httpGet:
                        path: /health
                        port: 80
                    initialDelaySeconds: 10
                    periodSeconds: 10
                    timeoutSeconds: 5
                    successThreshold: 1
                    failureThreshold: 3