name: Bug Report
description: File a bug report.
title: "[Heron UI Enhancement]: "
labels: ["enhancement", "improve"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this enhancement request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: whats-better
    attributes:
      label: What could be better?
      description: Tell us which feature you would like to improve?
      placeholder: How can we be better?
      value: "I like Heron Data, BUT..."
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
