name: CICD

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_KEY: ${{secrets.DOCKERHUB_KEY}}
  IMAGE_NAME: heron-ui

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{env.DOCKER_HUB_USERNAME}}
          password: ${{env.DOCKER_KEY}}

      - name: Build Docker Image
        run: docker build -t ${{env.DOCKER_HUB_USERNAME}}/${{env.IMAGE_NAME}}:${{github.sha}} .

      - name: Push Docker Image
        run: docker push ${{env.DOCKER_HUB_USERNAME}}/${{env.IMAGE_NAME}}:${{github.sha}}

      - name: Update Helm values.yml
        run: |
          cd heron-helm
          sed -i 's|APP_VERSION:.*|APP_VERSION: '${{github.sha}}'|' values.yaml
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update values.yaml"
          git push
